words = [
    "astro",
    "bashls",
    "bufnr",
    "catppuccin",
    "changedelete",
    "cssls",
    "cursorline",
    "djlint",
    "editorconfig",
    "endwise",
    "formatters",
    "fzf",
    "gitcommit",
    "gitsigns",
    "htmldjango",
    "ibl",
    "jsregexp",
    "jumplist",
    "kanagawa",
    "keymap",
    "keymaps",
    "lazydev",
    "lazypath",
    "leptos",
    "lspconfig",
    "luadoc",
    "luap",
    "mapleader",
    "neovim",
    "nvim",
    "prettierd",
    "ripgrep",
    "stylua",
    "textobjects",
    "topdelete",
    "undercurl",
    "vimdoc",
    "vscode",
    "yamlls",
]
